Readme updated
Ubn-Jr/hirob-be-core pull request #3
Opened 2023-09-05 06:12 UTC by Sddilora

2023-09-05 08:01 UTC, husamettinarabaci requested changes
Please fix the order of team members.
Team Lead
Team Members...

2023-09-05 08:33 UTC, Sddilora commented
oh, okay. I just followed the github's order.

2023-09-05 12:09 UTC, husamettinarabaci requested changes
I've written a comment about team members

2023-09-06 03:49 UTC, husamettinarabaci commented on README.md
> +[Dilara DOĞAN](https://github.com/Sddilora)
It is not for us. @Sddilora is the leader of the project and every team member has to know their responsibility and their team leader. Please fix it or you can choose to remove the supporter name from this list. It is a little bit easy way.

2023-09-06 06:39 UTC, husamettinarabaci approved these changes
Good Work

2023-09-06 06:39 UTC, merged